include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build job:
  extends: .container-builder
  variables:
    PERSIST_IMAGE_NAME: discard
    DOCKERFILE: ci/docker/Dockerfile
