include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - test

test job:
  extends: .container-runner-daint-gpu
  image: ubuntu:22.04
  stage: test
  script:
    - mkdir -p my_buildcache
    - ls -lh my_buildcache
    - echo 1234 > my_buildcache/some_file
  cache:
    key: build-cache
    paths:
      - my_buildcache/**
